[package]
name = "detect-checkerboard"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
image = "0.23.13"
imageproc = "0.22.0"
structopt = "0.3.0"
show-image = { version = "0.8.1", features = ["image", "save"] }
num = "0.3.0"
float-ord = "0.2.0"
